<a href="https://colab.research.google.com/github/Ayesha-Muneer/Data-Science-Lab/blob/master/CourseOutcome1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#numpy Introduction
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#Type functiom
print("Type of Array : ",type(a))

Type of Array :  <class 'numpy.ndarray'>


In [ ]:
#Dimension using ndim
print("Dimension of Array : ",a.ndim)

Dimension of Array :  2


In [ ]:
#Shape
print("Shape of Array : ",a.shape)

Shape of Array :  (2, 4)


In [ ]:
#size
print("Size of Array : ",a.size)

Size of Array :  8


In [ ]:
#List to array
l = [1, 2, 3, 4]
print(type(l)) #Type prints the type used
print(l)
a=np.asarray(l)
print(type(a))
print(a)


<class 'list'>
[1, 2, 3, 4]
<class 'numpy.ndarray'>
[1 2 3 4]


In [ ]:
#Tuple to array
t = ([1, 2], [3, 4])
print(type(t))
print(t)
a=np.asarray(t)
print(type(a))
print(a)

<class 'tuple'>
([1, 2], [3, 4])
<class 'numpy.ndarray'>
[[1 2]
 [3 4]]


In [ ]:
#1D Array
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [ ]:
#2D Array
a = ([[1, 2],[3,4]])
n = np.array(a)
print("Array :",n)
print("Dimension :",n.ndim)
print("Shape :",n.shape)

Array : [[1 2]
 [3 4]]
Dimension : 2
Shape : (2, 2)


In [ ]:
#Zeros function
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#Ones function
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#Ones function in integer
a=np.ones((3,3))
a=a.astype(int)
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
#eye function- Identity matrix
a=np.eye(3, dtype=int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
#range of numbers
print("Array from 2 to 8 : ",np.arange(2,9))

[2 3 4 5 6 7 8]


In [ ]:
#range of numbers with common diffrence
print("Array: ",np.arange(2,22,2))

Array:  [ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
#Addition
a=([1,2,3,4,5])
b=([5,4,3,2,1])
print("Sum is : ",np.add(a,b))

Sum is :  [6 6 6 6 6]


In [ ]:
#Subtraction
a=([1,2,3,4,5])
b=([5,4,3,2,1])
print("Diffrence is : ",np.subtract(a,b))
print("Diffrence is : ",np.subtract(b,a))

Diffrence is :  [-4 -2  0  2  4]
Diffrence is :  [ 4  2  0 -2 -4]


In [ ]:
#Multiplication
a=([1,2,3,4,5])
b=([5,4,3,2,1])
print("Multiplication : ",np.multiply(a,b))

Multiplication :  [5 8 9 8 5]


In [ ]:
#Division and reminder
a=([1,2,3,4,5])
b=([5,4,3,2,1])
print("Quotient is : ",np.divide(a,b))
print("Reminder is : ",np.mod(a,b))
print("Quotient and reminder is : ",np.divmod(a,b))


Quotient is :  [0.2 0.5 1.  2.  5. ]
Quotient is :  [1 2 0 0 0]
Quotient is :  (array([0, 0, 1, 2, 5]), array([1, 2, 0, 0, 0]))


In [ ]:
#Power
a=([1,2,3,4,5])
b=([5,4,3,2,1])
print("power is : ",np.power(a,b))
print("power is : ",np.power(a,2))

power is :  [ 1 16 27 16  5]
power is :  [ 1  4  9 16 25]


In [ ]:
#Absolute
a=np.array([-1,2,-3,4,-5,-6,7,-8])
print("Array is:",np.absolute(a))

Array is: [1 2 3 4 5 6 7 8]


In [ ]:
#linspace
np.linspace(2,7, num = 10,retstep=True, dtype=int)

(array([2, 2, 3, 3, 4, 4, 5, 5, 6, 7]), 0.5555555555555556)

In [ ]:
# Create an array filled with random values
a = np.random.random((2,2))  
print(a)

[[0.7986712  0.43262398]
 [0.35249827 0.42225914]]


In [ ]:
#Reshaping
a=np.array([1,2,3,4,5,6,7,8,9])
print("Array : ",a)
print("Array after reshaping:\n" ,a.reshape(3,3))

Array :  [1 2 3 4 5 6 7 8 9]
Array after reshaping:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#resizing
a = np.array([[1,2,3],[4,5,6]]) 
print("Array is :\n",a)
b=np.resize(a, (3,2))
print("Array after resizing :\n",b)
a.resize(3,2)
print("Array after resizing :\n",a)


Array is :
 [[1 2 3]
 [4 5 6]]
Array after resizing :
 [[1 2]
 [3 4]
 [5 6]]
Array after resizing :
 [[1 2]
 [3 4]
 [5 6]]


In [ ]:
from numpy.linalg import svd
np.linalg.svd(a)

(array([[-0.37616823, -0.92655138],
        [-0.92655138,  0.37616823]]),
 array([14.22740741,  1.25732984]),
 array([[-0.35206169, -0.44362578, -0.53518987, -0.62675396],
        [ 0.75898127,  0.3212416 , -0.11649807, -0.55423774],
        [-0.40008743,  0.25463292,  0.69099646, -0.54554195],
        [-0.37407225,  0.79697056, -0.47172438,  0.04882607]]))

In [ ]:
u,s,vt=svd(a,full_matrices=True)
print(u.shape,s.shape,vt.shape)

(2, 2) (2,) (4, 4)


In [ ]:
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(u)

[[-0.37616823 -0.92655138]
 [-0.92655138  0.37616823]]


In [ ]:
print(s)

[14.22740741  1.25732984]


In [ ]:
print(vt)

[[-0.35206169 -0.44362578 -0.53518987 -0.62675396]
 [ 0.75898127  0.3212416  -0.11649807 -0.55423774]
 [-0.40008743  0.25463292  0.69099646 -0.54554195]
 [-0.37407225  0.79697056 -0.47172438  0.04882607]]


In [ ]:
a.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])