<a href="https://colab.research.google.com/github/Ayesha-Muneer/Data-Science-Lab/blob/master/Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Python code to demonstrate matrix operations
# multiply() and dot()
  
# importing numpy for matrix operations
import numpy
  
# initializing matrices
x = numpy.array([[1, 2], [3, 4]])
y = numpy.array([[5, 6], [7, 8]])
print("Given matrix:")
print(x)
# using multiply() to multiply matrices element wise
print ("The element wise multiplication of matrix is : ")
print (numpy.multiply(x,y))
  
# using dot() to multiply matrices
print ("The product of matrices is : ")
print (numpy.dot(x,y))

# using "T" to transpose the matrix
print ("The transpose of given matrix is : ")
print (x.T)

# using "trace" to find trace of the matrix
print ("The trace of given matrix is : ")
print (x.trace())

#Rank of matrix
print(numpy.linalg.matrix_rank(x))

#Determinant of matrix
print(numpy.linalg.det(x))

#Inverse of matrix
print(numpy.linalg.inv(x))

#Eigen values of matrix
print(numpy.linalg.eig(x))

Given matrix:
[[1 2]
 [3 4]]
The element wise multiplication of matrix is : 
[[ 5 12]
 [21 32]]
The product of matrices is : 
[[19 22]
 [43 50]]
The transpose of given matrix is : 
[[1 3]
 [2 4]]
The trace of given matrix is : 
5
2
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
